# Form implementation generated from reading ui file 'D:\HK7\TDLT\Code\Chapter5\bmi_project\ui\BMIMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditWeight = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditWeight.setGeometry(QtCore.QRect(400, 211, 91, 31))
        self.lineEditWeight.setStyleSheet("QLineEdit {\n"
"    background-color: #F9FAFB;\n"
"    border: 1px solid #D1D5DB;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    color: #111827;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3B82F6;\n"
"    background-color: white;\n"
"}")
        self.lineEditWeight.setObjectName("lineEditWeight")
        self.exitSIgn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitSIgn.setGeometry(QtCore.QRect(410, 270, 93, 28))
        self.exitSIgn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 117, 119);\n"
"    color: #374151;\n"
"    border: 1px solid #D1D5DB;\n"
"    border-radius: 8px;\n"
"    padding: 8px 18px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E5E7EB;\n"
"}")
        self.exitSIgn.setObjectName("exitSIgn")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 270, 93, 28))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(37, 99, 235);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(29, 78, 216);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(294, 330, 51, 31))
        self.label_8.setStyleSheet("background-color: rgb(239, 246, 255);\n"
"color: rgb(37, 99, 235);\n"
"border-radius: 10px;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"font-align: central")
        self.label_8.setObjectName("label_8")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(190, 70, 401, 431))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 16px;\n"
"    border: 1px solid #E5E7EB;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(100, 100, 71, 16))
        self.label_4.setStyleSheet("color: black;\n"
"")
        self.label_4.setObjectName("label_4")
        self.lineEditHeight = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditHeight.setGeometry(QtCore.QRect(210, 90, 91, 31))
        self.lineEditHeight.setStyleSheet("QLineEdit {\n"
"    background-color: #F9FAFB;\n"
"    border: 1px solid #D1D5DB;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    color: #111827;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3B82F6;\n"
"    background-color: white;\n"
"}")
        self.lineEditHeight.setObjectName("lineEditHeight")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(100, 150, 71, 16))
        self.label_5.setStyleSheet("color: black")
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(parent=self.frame)
        self.label_9.setGeometry(QtCore.QRect(100, 330, 55, 31))
        self.label_9.setStyleSheet("background-color: rgb(236, 253, 245);\n"
"color: rgb(5, 150, 105);\n"
"border-radius: 10px;\n"
"font-weight: bold;")
        self.label_9.setObjectName("label_9")
        self.labelBMIresult = QtWidgets.QLabel(parent=self.frame)
        self.labelBMIresult.setGeometry(QtCore.QRect(170, 250, 141, 51))
        self.labelBMIresult.setStyleSheet("\n"
"color: black;\n"
"font-size: 15;\n"
" font-weight: bold;\n"
"")
        self.labelBMIresult.setObjectName("labelBMIresult")
        self.labelBMIresult_2 = QtWidgets.QLabel(parent=self.frame)
        self.labelBMIresult_2.setGeometry(QtCore.QRect(170, 320, 141, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelBMIresult_2.setFont(font)
        self.labelBMIresult_2.setStyleSheet("\n"
"color: black;\n"
"font-size: 10;\n"
" font-weight: bold;")
        self.labelBMIresult_2.setObjectName("labelBMIresult_2")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(80, 40, 250, 31))
        self.label.setStyleSheet("color:rgb(255, 0, 0);\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 30")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineEditHeight.raise_()
        self.label_9.raise_()
        self.labelBMIresult.raise_()
        self.labelBMIresult_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.frame.raise_()
        self.lineEditWeight.raise_()
        self.exitSIgn.raise_()
        self.pushButton.raise_()
        self.label_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.exitSIgn.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exitSIgn.setText(_translate("MainWindow", "Exit"))
        self.pushButton.setText(_translate("MainWindow", "Calc BMI"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">BMI </p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Height (m)"))
        self.label_5.setText(_translate("MainWindow", "Weight (kg)"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Status</p></body></html>"))
        self.labelBMIresult.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelBMIresult_2.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">BMI CALCULATION</span></p><p><br/></p></body></html>"))
