# Form implementation generated from reading ui file 'D:\HK7\TDLT\Code\Chapter5\Ex73\ui\MyMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 511)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label)
        self.enterALabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.enterALabel.setObjectName("enterALabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.enterALabel)
        self.enterALineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.enterALineEdit.setObjectName("enterALineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.enterALineEdit)
        self.enterBLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.enterBLabel.setObjectName("enterBLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.enterBLabel)
        self.enterBLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.enterBLineEdit.setObjectName("enterBLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.enterBLineEdit)
        self.enterCLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.enterCLabel.setObjectName("enterCLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.enterCLabel)
        self.enterCLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.enterCLineEdit.setObjectName("enterCLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.enterCLineEdit)
        self.resultLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.resultLabel.setObjectName("resultLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.resultLabel)
        self.resultLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.resultLineEdit.setObjectName("resultLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.resultLineEdit)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButton)
        self.verticalLayout.addLayout(self.formLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 742, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Quadratic Equation"))
        self.enterALabel.setText(_translate("MainWindow", "Enter a"))
        self.enterBLabel.setText(_translate("MainWindow", "Enter b"))
        self.enterCLabel.setText(_translate("MainWindow", "Enter c"))
        self.resultLabel.setText(_translate("MainWindow", "Result"))
        self.pushButton.setText(_translate("MainWindow", "Count"))
